[tools]
python = "latest"
node = "lts"
bun = "latest"
pipx = "latest"
uv = "latest"

# neovim
shfmt = "latest"
taplo = 'latest'
stylua = "latest"
lua-language-server = "latest"
ruff = "latest"
# "npm:bash-language-server" = "latest"
# "npm:@microsoft/compose-language-service" = "latest"
# "npm:@fsouza/prettierd" = "latest"
zls = "latest"
zig = "ref:master"

[settings]
experimental = true
npm.bun = true
python.uv_venv_auto = true
