#!/usr/bin/env zsh

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir/

# Add local scripts to PATH
export PATH="$HOME/.local/bin:$PATH"

# TERM
export TERM='xterm-256color'

# Neovim as editor
# TODO: consider making bespoke neovim configs
# BUG: does $NVIM_APPNAME need to be defined for these to work with the ~/.config/nvim/$NVIM_APPNAME structure? 
# Without defining $NVIM_APPNAME neovim will search for ~/.config/nvim/init.lua. It should be set in .zshrc and these are all interactive shell features
export EDITOR='nvim'
export VISUAL='nvim'
export MANPAGER='nvim +Man!'

# Clean home directory
export LESSHISTFILE=$XDG_CACHE_HOME/less/history
export PYTHONSTARTUP=$XDG_CONFIG_HOME/python/pythonrc
