#!/usr/bin/env zsh

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir/

# Term
export TERM='xterm-256color'

# Neovim as editor
export EDITOR='nvim'
export VISUAL='nvim'
export MANPAGER='nvim +Man!'

# Clean home directory
export LESSHISTFILE=$XDG_CACHE_HOME/less
export PYTHONSTARTUP=~/.config/python/pythonrc
export STARSHIP_CONFIG=XDG_CONFIG_HOME/starship/starship.toml
export STARSHIP_CACHE=$XDG_CACHE_HOME/starship
