auto_sync = true
update_check = false
style = "compact"
inline_height = 15
inline_height_shell_up_key_binding = 15
show_preview = true
show_numeric_shortcuts = false

# sync_address = "https://api.atuin.sh"
# sync_frequency = "0"

# prefix fulltext fuzzy skim
search_mode = "fuzzy"
search_mode_shell_up_key_binding = "fuzzy"

# possible values: "global", "host", "session", "session-preload", "directory", "workspace"
# consider using search.filters to customize the enablement and order of filter modes
filter_mode = "global"

## With workspace filtering enabled, Atuin will filter for commands executed
## in any directory within a git repository tree (default: false).
##
## To use workspace mode by default when available, set this to true and
## set filter_mode to "workspace" or leave it unspecified and
## set search.filters to include "workspace" before other filter modes.
# workspaces = true

# which filter mode to use when atuin is invoked from a shell up-key binding
# the accepted values are identical to those of "filter_mode"
# leave unspecified to use same mode set in "filter_mode"
filter_mode_shell_up_key_binding = "global"


## characters that count as a part of a word
# word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## number of context lines to show when scrolling by pages
# scroll_context_lines = 1


max_preview_height = 4
show_help = false
show_tabs = false
secrets_filter = true
enter_accept = true

## Defaults to false. If enabled, when triggered after &&, || or |, Atuin will complete commands to chain rather than replace the current line.
command_chaining = true

## Cursor style in each keymap mode.  If specified, the cursor style is changed
## in entering the cursor shape.  Available values are "default" and
## "{blink,steady}-{block,underline,bar}".
# keymap_cursor = { emacs = "blink-block", vim_insert = "blink-block", vim_normal = "steady-block" }

prefers_reduced_motion = true

[stats]
common_prefix = ["sudo"]
ignored_commands = ["cd", "ls"]
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "dotnet",
  "git",
  "go",
  "ip",
  "jj",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

[sync]
# TODO: check if this is still needed
records = true

[preview]
## which preview strategy to use to calculate the preview height (respects max_preview_height).
## possible values: auto, static
## auto: length of the selected command.
## static: length of the longest command stored in the history.
## fixed: use max_preview_height as fixed height.
strategy = "fixed"

[search]
filters = [
  "global",
  "host",
  "session",
  "session-preload",
  "workspace",
  "directory",
]

[ui]
columns = ["exit", "time", "duration", "command"]

[logs]
dir = "$XDG_STATE_HOME/atuin/logs"
