FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
FZF_DEFAULT_OPTS_FILE="$HOME/.config/fzf/config"

# CTRL-Y to copy the command into clipboard using pbcopy
FZF_CTRL_R_OPTS="--bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort' --color header:italic --header '<C-Y> copy to clipboard'"

FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"

FZF_ALT_C_COMMAND="" # use zoxide
