# dependencies
brew "neovim"
brew "imagemagick"

# language tools
brew "rust"
brew "go"
brew "gopls"
brew "basedpyright"
brew "ruff"
brew "lua-language-server"
brew "stylua"
brew "prettier"
brew "prettierd"
brew "bash-language-server"
brew "shfmt"
