# dependencies
brew "neovim"
brew "imagemagick"

# language servers
brew "basedpyright"
brew "ruff"
brew "lua-language-server"
brew "stylua"
brew "prettier"
brew "prettierd"
brew "bash-language-server"
